import { createContext, useContext, useState, useEffect } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

// Language translations
const translations = {
  en: {
    // Navigation
    features: "Features",
    contact: "Contact Us",
    login: "Login / Sign Up",
    dashboard: "Dashboard",
    logout: "Logout",
    welcome: "Welcome",
    
    // Landing Page
    heroTitle: "SELLER'S SPACE",
    heroSubtitle: "Welcome to the Future of Farming",
    getStarted: "Get Started Today",
    whyChoose: "Why Choose FarmPortal?",
    whyChooseDesc: "Our platform is designed specifically for farmers, providing all the tools you need to succeed in modern agriculture.",
    batchManagement: "Batch Management",
    batchManagementDesc: "Easily track and manage your crop batches from planting to harvest. Monitor progress and maintain detailed records.",
    ratingSystem: "Rating System",
    ratingSystemDesc: "Build your reputation with our transparent rating system. Quality produce leads to better ratings and more orders.",
    sustainableGrowth: "Sustainable Growth",
    sustainableGrowthDesc: "Promote sustainable farming practices with our eco-friendly guidelines and certification programs.",
    readyToTransform: "Ready to Transform Your Farming Business?",
    readyToTransformDesc: "Join thousands of farmers who are already using HerbiProof to increase their profits and streamline their operations.",
    startJourney: "Start Your Journey",
    
    // Dashboard
    farmerDashboard: "Farmer Dashboard",
    distributorDashboard: "Distributor Dashboard", 
    retailerDashboard: "Retailer Dashboard",
    manageFarm: "manage your farm operations",
    manageDistribution: "manage your distribution network",
    manageStore: "manage your store",
    totalCrops: "Total Crops",
    activeOrders: "Active Orders",
    averageRating: "Average Rating",
    thisMonthEarnings: "This Month Earnings",
    myCrops: "My Crops",
    orders: "Orders",
    ratings: "Ratings",
    tips: "Tips",
    addNewCrop: "Add New Crop",
    editProfile: "Edit Profile",
    recentOrders: "Recent Orders",
    myRatings: "My Ratings",
    farmingTips: "Farming Tips",
    noRatingsYet: "No ratings yet.",
    retailerNetwork: "Retailer Network",
    retailerNetworkDesc: "Retailer network information will be here.",
    myStock: "My Stock",
    logistics: "Logistics",
    network: "Network",
    addNewStock: "Add New Stock",
    activeDeliveries: "Active Deliveries",
    myProducts: "My Products",
    customers: "Customers",
    sales: "Sales",
    addNewProduct: "Add New Product",
    salesOverview: "Sales Overview",
    myCustomers: "My Customers",
    customerInfo: "Customer information will be here.",
    
    // Common
    quantity: "Quantity",
    price: "Price",
    status: "Status",
    amount: "Amount",
    date: "Date",
    phone: "Phone",
    edit: "Edit",
    call: "Call",
    available: "Available",
    lowStock: "Low Stock",
    soldOut: "Sold Out",
    confirmed: "Confirmed",
    pending: "Pending",
    delivered: "Delivered",
    processing: "Processing",
    shipped: "Shipped",
    inStock: "In Stock",
    inTransit: "In Transit",
    scheduled: "Scheduled"
  },
  
  hi: {
    // Navigation
    features: "विशेषताएं",
    contact: "संपर्क करें",
    login: "लॉगिन / साइन अप",
    dashboard: "डैशबोर्ड",
    logout: "लॉगआउट",
    welcome: "स्वागत",
    
    // Landing Page
    heroTitle: "विक्रेता स्थान",
    heroSubtitle: "कृषि के भविष्य में आपका स्वागत है",
    getStarted: "आज ही शुरू करें",
    whyChoose: "फार्मपोर्टल क्यों चुनें?",
    whyChooseDesc: "हमारा प्लेटफॉर्म विशेष रूप से किसानों के लिए डिज़ाइन किया गया है, जो आधुनिक कृषि में सफलता के लिए आवश्यक सभी उपकरण प्रदान करता है।",
    batchManagement: "बैच प्रबंधन",
    batchManagementDesc: "रोपण से कटाई तक अपने फसल बैचों को आसानी से ट्रैक और प्रबंधित करें। प्रगति की निगरानी करें और विस्तृत रिकॉर्ड रखें।",
    ratingSystem: "रेटिंग सिस्टम",
    ratingSystemDesc: "हमारे पारदर्शी रेटिंग सिस्टम के साथ अपनी प्रतिष्ठा बनाएं। गुणवत्तापूर्ण उत्पाद बेहतर रेटिंग और अधिक ऑर्डर लाते हैं।",
    sustainableGrowth: "सतत विकास",
    sustainableGrowthDesc: "हमारे पर्यावरण-अनुकूल दिशानिर्देशों और प्रमाणन कार्यक्रमों के साथ सतत कृषि प्रथाओं को बढ़ावा दें।",
    readyToTransform: "अपने कृषि व्यवसाय को बदलने के लिए तैयार हैं?",
    readyToTransformDesc: "हजारों किसानों के साथ जुड़ें जो पहले से ही अपने मुनाफे को बढ़ाने और अपने कार्यों को सुव्यवस्थित करने के लिए हर्बीप्रूफ का उपयोग कर रहे हैं।",
    startJourney: "अपनी यात्रा शुरू करें",
    
    // Dashboard
    farmerDashboard: "किसान डैशबोर्ड",
    distributorDashboard: "वितरक डैशबोर्ड",
    retailerDashboard: "रिटेलर डैशबोर्ड",
    manageFarm: "अपने खेत के काम संभालें",
    manageDistribution: "अपने वितरण नेटवर्क का प्रबंधन करें",
    manageStore: "अपने स्टोर का प्रबंधन करें",
    totalCrops: "कुल फसलें",
    activeOrders: "सक्रिय ऑर्डर",
    averageRating: "औसत रेटिंग",
    thisMonthEarnings: "इस महीने की कमाई",
    myCrops: "मेरी फसलें",
    orders: "ऑर्डर",
    ratings: "रेटिंग",
    tips: "टिप्स",
    addNewCrop: "नई फसल जोड़ें",
    editProfile: "प्रोफ़ाइल संपादित करें",
    recentOrders: "हाल के ऑर्डर",
    myRatings: "मेरी रेटिंग",
    farmingTips: "खेती के टिप्स",
    noRatingsYet: "अभी कोई रेटिंग नहीं है।",
    retailerNetwork: "रिटेलर नेटवर्क",
    retailerNetworkDesc: "रिटेलर नेटवर्क की जानकारी यहाँ होगी।",
    myStock: "मेरा स्टॉक",
    logistics: "लॉजिस्टिक्स",
    network: "नेटवर्क",
    addNewStock: "नया स्टॉक जोड़ें",
    activeDeliveries: "सक्रिय डिलीवरी",
    myProducts: "मेरे उत्पाद",
    customers: "ग्राहक",
    sales: "बिक्री",
    addNewProduct: "नया उत्पाद जोड़ें",
    salesOverview: "बिक्री अवलोकन",
    myCustomers: "मेरे ग्राहक",
    customerInfo: "ग्राहक की जानकारी यहाँ होगी।",
    
    // Common
    quantity: "मात्रा",
    price: "मूल्य",
    status: "स्थिति",
    amount: "राशि",
    date: "दिनांक",
    phone: "फोन",
    edit: "संपादित करें",
    call: "कॉल करें",
    available: "उपलब्ध",
    lowStock: "कम स्टॉक",
    soldOut: "बिका हुआ",
    confirmed: "पुष्टि की गई",
    pending: "लंबित",
    delivered: "वितरित",
    processing: "प्रसंस्करण",
    shipped: "भेजा गया",
    inStock: "स्टॉक में",
    inTransit: "परिवहन में",
    scheduled: "निर्धारित"
  },
  
  bn: {
    // Navigation
    features: "বৈশিষ্ট্য",
    contact: "যোগাযোগ",
    login: "লগইন / সাইন আপ",
    dashboard: "ড্যাশবোর্ড",
    logout: "লগআউট",
    welcome: "স্বাগতম",
    
    // Landing Page
    heroTitle: "বিক্রেতার স্থান",
    heroSubtitle: "কৃষির ভবিষ্যতে স্বাগতম",
    getStarted: "আজই শুরু করুন",
    whyChoose: "কেন ফার্মপোর্টাল বেছে নেবেন?",
    whyChooseDesc: "আমাদের প্ল্যাটফর্ম বিশেষভাবে কৃষকদের জন্য ডিজাইন করা হয়েছে, যা আধুনিক কৃষিতে সফলতার জন্য প্রয়োজনীয় সমস্ত সরঞ্জাম প্রদান করে।",
    batchManagement: "ব্যাচ ব্যবস্থাপনা",
    batchManagementDesc: "রোপণ থেকে ফসল কাটা পর্যন্ত আপনার ফসলের ব্যাচগুলি সহজেই ট্র্যাক এবং পরিচালনা করুন। অগ্রগতি নিরীক্ষণ করুন এবং বিস্তারিত রেকর্ড রাখুন।",
    ratingSystem: "রেটিং সিস্টেম",
    ratingSystemDesc: "আমাদের স্বচ্ছ রেটিং সিস্টেমের সাথে আপনার খ্যাতি গড়ে তুলুন। মানসম্পন্ন পণ্য ভাল রেটিং এবং আরও অর্ডার আনে।",
    sustainableGrowth: "টেকসই বৃদ্ধি",
    sustainableGrowthDesc: "আমাদের পরিবেশ-বান্ধব নির্দেশিকা এবং সার্টিফিকেশন প্রোগ্রামের সাথে টেকসই কৃষি অনুশীলন প্রচার করুন।",
    readyToTransform: "আপনার কৃষি ব্যবসা রূপান্তর করতে প্রস্তুত?",
    readyToTransformDesc: "হাজার হাজার কৃষকের সাথে যোগ দিন যারা ইতিমধ্যে তাদের মুনাফা বাড়াতে এবং তাদের কার্যক্রম সুবিন্যস্ত করতে হার্বিপ্রুফ ব্যবহার করছেন।",
    startJourney: "আপনার যাত্রা শুরু করুন",
    
    // Dashboard
    farmerDashboard: "কৃষক ড্যাশবোর্ড",
    distributorDashboard: "বিতরণকারী ড্যাশবোর্ড",
    retailerDashboard: "খুচরা বিক্রেতা ড্যাশবোর্ড",
    manageFarm: "আপনার খামারের কার্যক্রম পরিচালনা করুন",
    manageDistribution: "আপনার বিতরণ নেটওয়ার্ক পরিচালনা করুন",
    manageStore: "আপনার দোকান পরিচালনা করুন",
    totalCrops: "মোট ফসল",
    activeOrders: "সক্রিয় অর্ডার",
    averageRating: "গড় রেটিং",
    thisMonthEarnings: "এই মাসের আয়",
    myCrops: "আমার ফসল",
    orders: "অর্ডার",
    ratings: "রেটিং",
    tips: "টিপস",
    addNewCrop: "নতুন ফসল যোগ করুন",
    editProfile: "প্রোফাইল সম্পাদনা করুন",
    recentOrders: "সাম্প্রতিক অর্ডার",
    myRatings: "আমার রেটিং",
    farmingTips: "কৃষি টিপস",
    noRatingsYet: "এখনো কোনো রেটিং নেই।",
    retailerNetwork: "খুচরা বিক্রেতা নেটওয়ার্ক",
    retailerNetworkDesc: "খুচরা বিক্রেতা নেটওয়ার্কের তথ্য এখানে থাকবে।",
    myStock: "আমার স্টক",
    logistics: "লজিস্টিক্স",
    network: "নেটওয়ার্ক",
    addNewStock: "নতুন স্টক যোগ করুন",
    activeDeliveries: "সক্রিয় ডেলিভারি",
    myProducts: "আমার পণ্য",
    customers: "গ্রাহক",
    sales: "বিক্রয়",
    addNewProduct: "নতুন পণ্য যোগ করুন",
    salesOverview: "বিক্রয় ওভারভিউ",
    myCustomers: "আমার গ্রাহক",
    customerInfo: "গ্রাহকের তথ্য এখানে থাকবে।",
    
    // Common
    quantity: "পরিমাণ",
    price: "দাম",
    status: "অবস্থা",
    amount: "পরিমাণ",
    date: "তারিখ",
    phone: "ফোন",
    edit: "সম্পাদনা করুন",
    call: "কল করুন",
    available: "উপলব্ধ",
    lowStock: "কম স্টক",
    soldOut: "বিক্রি শেষ",
    confirmed: "নিশ্চিত",
    pending: "মুলতবি",
    delivered: "ডেলিভারি",
    processing: "প্রক্রিয়াকরণ",
    shipped: "পাঠানো হয়েছে",
    inStock: "স্টকে আছে",
    inTransit: "পথে",
    scheduled: "নির্ধারিত"
  },
  
  te: {
    // Navigation
    features: "విశేషాలు",
    contact: "సంప్రదించండి",
    login: "లాగిన్ / సైన్ అప్",
    dashboard: "డ్యాష్‌బోర్డ్",
    logout: "లాగ్‌అవుట్",
    welcome: "స్వాగతం",
    
    // Landing Page
    heroTitle: "విక్రేత స్థలం",
    heroSubtitle: "వ్యవసాయ భవిష్యత్తుకు స్వాగతం",
    getStarted: "ఈరోజే ప్రారంభించండి",
    whyChoose: "ఎందుకు ఫార్మ్‌పోర్టల్‌ను ఎంచుకోవాలి?",
    whyChooseDesc: "మా ప్లాట్‌ఫారమ్‌ను ప్రత్యేకంగా రైతుల కోసం రూపొందించారు, ఇది ఆధునిక వ్యవసాయంలో విజయం సాధించడానికి అవసరమైన అన్ని సాధనాలను అందిస్తుంది.",
    batchManagement: "బ్యాచ్ నిర్వహణ",
    batchManagementDesc: "నాటడం నుండి పంట కోత వరకు మీ పంట బ్యాచ్‌లను సులభంగా ట్రాక్ చేయండి మరియు నిర్వహించండి. పురోగతిని పర్యవేక్షించండి మరియు వివరణాత్మక రికార్డ్‌లను నిర్వహించండి.",
    ratingSystem: "రేటింగ్ వ్యవస్థ",
    ratingSystemDesc: "మా పారదర్శక రేటింగ్ వ్యవస్థతో మీ ప్రతిష్ఠను నిర్మించండి. నాణ్యమైన ఉత్పత్తులు మంచి రేటింగ్‌లు మరియు ఎక్కువ ఆర్డర్‌లను తెస్తాయి.",
    sustainableGrowth: "స్థిరమైన వృద్ధి",
    sustainableGrowthDesc: "మా పర్యావరణ-స్నేహప్రియమైన మార్గదర్శకాలతో మరియు ధృవీకరణ కార్యక్రమాలతో స్థిరమైన వ్యవసాయ పద్ధతులను ప్రోత్సహించండి.",
    readyToTransform: "మీ వ్యవసాయ వ్యాపారాన్ని మార్చడానికి సిద్ధమా?",
    readyToTransformDesc: "వారి లాభాలను పెంచడానికి మరియు వారి కార్యకలాపాలను సులభతరం చేయడానికి ఇప్పటికే హెర్బిప్రూఫ్‌ను ఉపయోగిస్తున్న వేలాది రైతులతో చేరండి.",
    startJourney: "మీ ప్రయాణాన్ని ప్రారంభించండి",
    
    // Dashboard
    farmerDashboard: "రైతు డ్యాష్‌బోర్డ్",
    distributorDashboard: "వితరణకర్త డ్యాష్‌బోర్డ్",
    retailerDashboard: "రిటైలర్ డ్యాష్‌బోర్డ్",
    manageFarm: "మీ వ్యవసాయ కార్యకలాపాలను నిర్వహించండి",
    manageDistribution: "మీ వితరణ నెట్‌వర్క్‌ను నిర్వహించండి",
    manageStore: "మీ స్టోర్‌ను నిర్వహించండి",
    totalCrops: "మొత్తం పంటలు",
    activeOrders: "క్రియాశీల ఆర్డర్‌లు",
    averageRating: "సగటు రేటింగ్",
    thisMonthEarnings: "ఈ నెల ఆదాయం",
    myCrops: "నా పంటలు",
    orders: "ఆర్డర్‌లు",
    ratings: "రేటింగ్‌లు",
    tips: "చిట్కాలు",
    addNewCrop: "కొత్త పంట జోడించండి",
    editProfile: "ప్రొఫైల్ సవరించండి",
    recentOrders: "ఇటీవలి ఆర్డర్‌లు",
    myRatings: "నా రేటింగ్‌లు",
    farmingTips: "వ్యవసాయ చిట్కాలు",
    noRatingsYet: "ఇంకా రేటింగ్‌లు లేవు.",
    retailerNetwork: "రిటైలర్ నెట్‌వర్క్",
    retailerNetworkDesc: "రిటైలర్ నెట్‌వర్క్ సమాచారం ఇక్కడ ఉంటుంది.",
    myStock: "నా స్టాక్",
    logistics: "లాజిస్టిక్స్",
    network: "నెట్‌వర్క్",
    addNewStock: "కొత్త స్టాక్ జోడించండి",
    activeDeliveries: "క్రియాశీల డెలివరీలు",
    myProducts: "నా ఉత్పత్తులు",
    customers: "కస్టమర్‌లు",
    sales: "విక్రయాలు",
    addNewProduct: "కొత్త ఉత్పత్తి జోడించండి",
    salesOverview: "విక్రయ అవలోకనం",
    myCustomers: "నా కస్టమర్‌లు",
    customerInfo: "కస్టమర్ సమాచారం ఇక్కడ ఉంటుంది.",
    
    // Common
    quantity: "పరిమాణం",
    price: "ధర",
    status: "స్థితి",
    amount: "మొత్తం",
    date: "తేదీ",
    phone: "ఫోన్",
    edit: "సవరించండి",
    call: "కాల్ చేయండి",
    available: "అందుబాటులో",
    lowStock: "తక్కువ స్టాక్",
    soldOut: "అమ్ముడైంది",
    confirmed: "నిర్ధారించబడింది",
    pending: "వేచి ఉంది",
    delivered: "డెలివర్ చేయబడింది",
    processing: "ప్రాసెస్ చేస్తోంది",
    shipped: "అమ్ముడుపోయింది",
    inStock: "స్టాక్‌లో ఉంది",
    inTransit: "ప్రయాణంలో",
    scheduled: "నిర్ణయించబడింది"
  },
  
  ta: {
    // Navigation
    features: "அம்சங்கள்",
    contact: "தொடர்பு கொள்ளுங்கள்",
    login: "உள்நுழை / பதிவு",
    dashboard: "டாஷ்போர்டு",
    logout: "வெளியேறு",
    welcome: "வரவேற்கிறோம்",
    
    // Landing Page
    heroTitle: "விற்பனையாளர் இடம்",
    heroSubtitle: "வேளாண்மையின் எதிர்காலத்திற்கு வரவேற்கிறோம்",
    getStarted: "இன்றே தொடங்குங்கள்",
    whyChoose: "ஏன் ஃபார்ம்போர்ட்டலை தேர்ந்தெடுக்க வேண்டும்?",
    whyChooseDesc: "எங்கள் தளம் குறிப்பாக விவசாயிகளுக்காக வடிவமைக்கப்பட்டுள்ளது, இது நவீன வேளாண்மையில் வெற்றி பெற தேவையான அனைத்து கருவிகளையும் வழங்குகிறது.",
    batchManagement: "தொகுப்பு மேலாண்மை",
    batchManagementDesc: "நடவு முதல் அறுவடை வரை உங்கள் பயிர் தொகுப்புகளை எளிதாக கண்காணித்து நிர்வகிக்கவும். முன்னேற்றத்தை கண்காணித்து விரிவான பதிவுகளை பராமரிக்கவும்.",
    ratingSystem: "மதிப்பீட்டு அமைப்பு",
    ratingSystemDesc: "எங்கள் வெளிப்படையான மதிப்பீட்டு அமைப்புடன் உங்கள் நற்பெயரை உருவாக்குங்கள். தரமான உற்பத்தி சிறந்த மதிப்பீடுகள் மற்றும் அதிக ஆர்டர்களை கொண்டு வருகிறது.",
    sustainableGrowth: "நிலையான வளர்ச்சி",
    sustainableGrowthDesc: "எங்கள் சூழல் நட்பு வழிகாட்டுதல்கள் மற்றும் சான்றிதழ் திட்டங்களுடன் நிலையான வேளாண்மை நடைமுறைகளை ஊக்குவிக்கவும்.",
    readyToTransform: "உங்கள் வேளாண்மை வணிகத்தை மாற்ற தயாரா?",
    readyToTransformDesc: "தங்கள் லாபத்தை அதிகரிக்கவும் தங்கள் செயல்பாடுகளை சீரமைக்கவும் ஏற்கனவே ஹெர்பிப்ரூஃப் பயன்படுத்தும் ஆயிரக்கணக்கான விவசாயிகளுடன் சேருங்கள்.",
    startJourney: "உங்கள் பயணத்தை தொடங்குங்கள்",
    
    // Dashboard
    farmerDashboard: "விவசாயி டாஷ்போர்டு",
    distributorDashboard: "விநியோகஸ்தர் டாஷ்போர்டு",
    retailerDashboard: "சில்லறை விற்பனையாளர் டாஷ்போர்டு",
    manageFarm: "உங்கள் பண்ணை செயல்பாடுகளை நிர்வகிக்கவும்",
    manageDistribution: "உங்கள் விநியோக நெட்வொர்க்கை நிர்வகிக்கவும்",
    manageStore: "உங்கள் கடையை நிர்வகிக்கவும்",
    totalCrops: "மொத்த பயிர்கள்",
    activeOrders: "செயலில் உள்ள ஆர்டர்கள்",
    averageRating: "சராசரி மதிப்பீடு",
    thisMonthEarnings: "இந்த மாத வருமானம்",
    myCrops: "என் பயிர்கள்",
    orders: "ஆர்டர்கள்",
    ratings: "மதிப்பீடுகள்",
    tips: "குறிப்புகள்",
    addNewCrop: "புதிய பயிர் சேர்க்கவும்",
    editProfile: "சுயவிவரத்தை திருத்தவும்",
    recentOrders: "சமீபத்திய ஆர்டர்கள்",
    myRatings: "என் மதிப்பீடுகள்",
    farmingTips: "வேளாண்மை குறிப்புகள்",
    noRatingsYet: "இன்னும் மதிப்பீடுகள் இல்லை.",
    retailerNetwork: "சில்லறை விற்பனையாளர் நெட்வொர்க்",
    retailerNetworkDesc: "சில்லறை விற்பனையாளர் நெட்வொர்க் தகவல் இங்கே இருக்கும்.",
    myStock: "என் பங்கு",
    logistics: "தளவாடங்கள்",
    network: "நெட்வொர்க்",
    addNewStock: "புதிய பங்கு சேர்க்கவும்",
    activeDeliveries: "செயலில் உள்ள டெலிவரிகள்",
    myProducts: "என் தயாரிப்புகள்",
    customers: "வாடிக்கையாளர்கள்",
    sales: "விற்பனை",
    addNewProduct: "புதிய தயாரிப்பு சேர்க்கவும்",
    salesOverview: "விற்பனை கண்ணோட்டம்",
    myCustomers: "என் வாடிக்கையாளர்கள்",
    customerInfo: "வாடிக்கையாளர் தகவல் இங்கே இருக்கும்.",
    
    // Common
    quantity: "அளவு",
    price: "விலை",
    status: "நிலை",
    amount: "தொகை",
    date: "தேதி",
    phone: "தொலைபேசி",
    edit: "திருத்தவும்",
    call: "அழைக்கவும்",
    available: "கிடைக்கிறது",
    lowStock: "குறைந்த பங்கு",
    soldOut: "விற்றுவிட்டது",
    confirmed: "உறுதிப்படுத்தப்பட்டது",
    pending: "நிலுவையில்",
    delivered: "வழங்கப்பட்டது",
    processing: "செயலாக்கப்படுகிறது",
    shipped: "அனுப்பப்பட்டது",
    inStock: "பங்கில் உள்ளது",
    inTransit: "போக்குவரத்தில்",
    scheduled: "திட்டமிடப்பட்டது"
  },
  mr: {
    heroSubtitle: "शेतीच्या भविष्यात आपले स्वागत",
    heroTitle: "विक्रेता जागा",
    whyChoose: "फार्मपोर्टल का निवडावे?",
    whyChooseDesc: "आमचे प्लॅटफॉर्म विशेषतः शेतकऱ्यांसाठी डिझाइन केलेले आहे, जे आपल्याला आधुनिक शेतीत यशस्वी होण्यासाठी आवश्यक सर्व साधने प्रदान करते.",
    batchManagement: "बॅच व्यवस्थापन",
    batchManagementDesc: "लागवडीपासून कापणीपर्यंत आपल्या पिकांच्या बॅचचे सहज ट्रॅक आणि व्यवस्थापन करा. प्रगतीचे निरीक्षण करा आणि तपशीलवार रेकॉर्ड ठेवा.",
    ratingSystem: "रेटिंग प्रणाली",
    ratingSystemDesc: "आमच्या पारदर्शक रेटिंग प्रणालीसह आपली प्रतिष्ठा तयार करा. गुणवत्तापूर्ण उत्पादन चांगल्या रेटिंग आणि अधिक ऑर्डरची ओळख करून देते.",
    sustainableGrowth: "स्थायी विकास",
    sustainableGrowthDesc: "आमच्या पर्यावरण-अनुकूल दिशानिर्देश आणि प्रमाणन कार्यक्रमांसह स्थायी शेती पद्धतींना प्रोत्साहन द्या.",
    readyToTransform: "आपला शेती व्यवसाय बदलण्यास तयार आहात?",
    readyToTransformDesc: "हजारो शेतकऱ्यांमध्ये सामील व्हा जे आपला नफा वाढवण्यासाठी आणि आपल्या कार्यप्रणालीला सुव्यवस्थित करण्यासाठी आधीच हर्बीप्रूफ वापरत आहेत.",
    getStarted: "आजच सुरु करा",
    startJourney: "आपली प्रवास सुरु करा",
    features: "वैशिष्ट्ये",
    contact: "आमच्याशी संपर्क साधा",
    dashboard: "डॅशबोर्ड",
    welcome: "स्वागत",
    logout: "लॉगआउट",
    login: "लॉगिन / साइन अप",
    farmerDashboard: "शेतकरी डॅशबोर्ड",
    helloWelcome: "नमस्कार! स्वागत आहे",
    sellCropsEarnMoney: "आपली पिके विका आणि पैसे कमवा",
    totalCrops: "एकूण पिके",
    activeOrders: "सक्रिय ऑर्डर",
    rating: "रेटिंग",
    earnings: "कमाई",
    quickActions: "द्रुत क्रिया",
    addNewCrop: "नवीन पीक जोडा",
    viewAllOrders: "सर्व ऑर्डर पहा",
    harvestTime: "कापणीची वेळ",
    manageProfile: "प्रोफाइल व्यवस्थापित करा",
    overview: "ओव्हरव्ह्यू",
    myCrops: "माझी पिके",
    orders: "ऑर्डर",
    recentActivity: "अलीकडील क्रियाकलाप",
    newOrderReceived: "नवीन ऑर्डर मिळाले",
    cropStatusUpdate: "पीक स्थिती अपडेट",
    lowStock: "कमी स्टॉक",
    newRatingReceived: "नवीन रेटिंग मिळाले",
    farmerTips: "शेतकरी टिप्स",
    tipTakePhotos: "टिप: आपल्या पिकांच्या फोटो घ्या - आपल्याला चांगली किंमत मिळेल",
    tipUpdatePrices: "सल्ला: नियमितपणे किंमती अपडेट करत रहा",
    tipGoodCustomerService: "लक्षात ठेवा: ग्राहकांसोबत चांगे संबंध ठेवा",
    quantity: "प्रमाण",
    price: "किंमत",
    quality: "गुणवत्ता",
    location: "स्थान",
    added: "जोडले",
    edit: "संपादित करा",
    buyer: "खरेदीदार",
    crop: "पीक",
    amount: "रक्कम",
    date: "तारीख",
    phone: "फोन",
    call: "कॉल करा",
    available: "उपलब्ध",
    sold: "विकले",
    confirmed: "पुष्टी केली",
    pending: "प्रलंबित",
    delivered: "पोचवले",
    back: "मागे",
    profile: "प्रोफाइल",
    distributorDashboard: "वितरक डॅशबोर्ड",
    manageDistributionNetwork: "आपल्या वितरण नेटवर्क आणि लॉजिस्टिक्सचे व्यवस्थापन करा",
    totalInventory: "एकूण इन्व्हेंटरी",
    revenue: "उत्पन्न",
    addInventory: "इन्व्हेंटरी जोडा",
    scheduleDelivery: "डिलिव्हरी शेड्यूल करा",
    inventory: "इन्व्हेंटरी",
    logistics: "लॉजिस्टिक्स",
    recentActivity: "अलीकडील क्रियाकलाप",
    inventoryStatusUpdated: "इन्व्हेंटरी स्थिती अपडेट केली",
    deliveryCompleted: "डिलिव्हरी पूर्ण झाली",
    distributionTips: "वितरण टिप्स",
    tipKeepTrackOfInventory: "टिप: स्टॉकआउट टाळण्यासाठी इन्व्हेंटरी पातळीवर नजर ठेवा",
    adviceOptimizeRoutes: "सल्ला: खर्च कमी करण्यासाठी डिलिव्हरी मार्ग अनुकूलित करा",
    rememberGoodSupplierRelations: "लक्षात ठेवा: पुरवठादारांसोबत चांगे संबंध ठेवा",
    product: "उत्पादन",
    supplier: "पुरवठादार",
    inStock: "स्टॉकमध्ये",
    outOfStock: "स्टॉक संपले",
    inTransit: "प्रवासात",
    track: "ट्रॅक करा",
    deliverySchedule: "डिलिव्हरी शेड्यूल",
    delivery: "डिलिव्हरी",
    vehicleStatus: "वाहन स्थिती",
    truckA: "ट्रक ए",
    truckB: "ट्रक बी",
    vanC: "व्हॅन सी",
    maintenance: "देखभाल",
    retailerDashboard: "किरकोळ विक्रेता डॅशबोर्ड",
    manageRetailOperations: "आपल्या किरकोळ कार्यप्रणाली आणि ग्राहक संबंधांचे व्यवस्थापन करा",
    totalProducts: "एकूण उत्पादने",
    customerRating: "ग्राहक रेटिंग",
    sales: "विक्री",
    addProduct: "उत्पादन जोडा",
    manageStore: "स्टोअर व्यवस्थापित करा",
    customerSupport: "ग्राहक सहायता",
    myProducts: "माझी उत्पादने",
    customers: "ग्राहक",
    productStatusUpdated: "उत्पादन स्थिती अपडेट केली",
    customerReviewReceived: "ग्राहक समीक्षा मिळाली",
    retailTips: "किरकोळ टिप्स",
    tipKeepProductsFresh: "टिप: ग्राहकांना आकर्षित करण्यासाठी उत्पादने ताजी आणि चांगल्या प्रकारे प्रदर्शित ठेवा",
    adviceMaintainSupplierRelations: "सल्ला: चांगल्या किंमतीसाठी पुरवठादारांसोबत चांगे संबंध ठेवा",
    rememberCustomerService: "लक्षात ठेवा: निष्ठा तयार करण्यासाठी ग्राहक सेवा महत्वाची आहे",
    category: "श्रेणी",
    customer: "ग्राहक",
    contactCustomer: "संपर्क करा",
    topCustomers: "शीर्ष ग्राहक",
    ordersThisMonth: "या महिन्यात ऑर्डर",
    vip: "व्हीआयपी",
    regular: "नियमित",
    new: "नवीन",
    customerFeedback: "ग्राहक अभिप्राय",
    excellentQuality: "उत्कृष्ट गुणवत्तेची उत्पादने!",
    goodService: "चांगी सेवा, वेगवान डिलिव्हरी",
    processing: "प्रक्रिया करत आहे",
    shipped: "पाठवले",
    inStock: "स्टॉकमध्ये",
    inTransit: "प्रवासात",
    scheduled: "शेड्यूल केले"
  },
  gu: {
    heroSubtitle: "ખેતીના ભવિષ્યમાં આપનું સ્વાગત",
    heroTitle: "વિક્રેતા સ્થાન",
    whyChoose: "ફાર્મપોર્ટલ કેમ પસંદ કરવું?",
    whyChooseDesc: "અમારું પ્લેટફોર્મ ખાસ કરીને ખેડૂતો માટે ડિઝાઇન કરવામાં આવ્યું છે, જે તમને આધુનિક ખેતીમાં સફળ થવા માટે જરૂરી બધા સાધનો પ્રદાન કરે છે.",
    batchManagement: "બેચ વ્યવસ્થાપન",
    batchManagementDesc: "લાગવાથી લઈને કાપણી સુધી તમારી પાકની બેચને સરળતાથી ટ્રેક અને વ્યવસ્થાપન કરો. પ્રગતિનું નિરીક્ષણ કરો અને વિગતવાર રેકોર્ડ રાખો.",
    ratingSystem: "રેટિંગ સિસ્ટમ",
    ratingSystemDesc: "અમારી પારદર્શક રેટિંગ સિસ્ટમ સાથે તમારી પ્રતિષ્ઠા બનાવો. ગુણવત્તાપૂર્ણ ઉત્પાદન વધુ સારા રેટિંગ અને વધુ ઓર્ડર તરફ દોરી જાય છે.",
    sustainableGrowth: "ટકાઉ વિકાસ",
    sustainableGrowthDesc: "અમારા પર્યાવરણ-અનુકૂળ દિશાનિર્દેશો અને પ્રમાણીકરણ કાર્યક્રમો સાથે ટકાઉ ખેતી પદ્ધતિઓને પ્રોત્સાહન આપો.",
    readyToTransform: "તમારા ખેતી વ્યવસાયને બદલવા માટે તૈયાર છો?",
    readyToTransformDesc: "હજારો ખેડૂતોમાં જોડાઓ જે પહેલેથી જ હર્બીપ્રૂફનો ઉપયોગ કરીને પોતાનો નફો વધારવા અને પોતાની કામગીરીને સુવ્યવસ્થિત કરવા માટે કરી રહ્યા છે.",
    getStarted: "આજે જ શરૂ કરો",
    startJourney: "તમારી યાત્રા શરૂ કરો",
    features: "વિશેષતાઓ",
    contact: "અમારો સંપર્ક કરો",
    dashboard: "ડેશબોર્ડ",
    welcome: "સ્વાગત",
    logout: "લોગઆઉટ",
    login: "લોગિન / સાઇન અપ",
    farmerDashboard: "ખેડૂત ડેશબોર્ડ",
    helloWelcome: "નમસ્કાર! સ્વાગત છે",
    sellCropsEarnMoney: "તમારા પાક વેચો અને પૈસા કમાઓ",
    totalCrops: "કુલ પાક",
    activeOrders: "સક્રિય ઓર્ડર",
    rating: "રેટિંગ",
    earnings: "કમાઈ",
    quickActions: "ઝડપી ક્રિયાઓ",
    addNewCrop: "નવો પાક ઉમેરો",
    viewAllOrders: "બધા ઓર્ડર જુઓ",
    harvestTime: "કાપણીનો સમય",
    manageProfile: "પ્રોફાઇલ મેનેજ કરો",
    overview: "અવલોકન",
    myCrops: "મારા પાક",
    orders: "ઓર્ડર",
    recentActivity: "તાજેતરની પ્રવૃત્તિ",
    newOrderReceived: "નવો ઓર્ડર મળ્યો",
    cropStatusUpdate: "પાક સ્થિતિ અપડેટ",
    lowStock: "ઓછો સ્ટોક",
    newRatingReceived: "નવી રેટિંગ મળી",
    farmerTips: "ખેડૂત ટિપ્સ",
    tipTakePhotos: "ટિપ: તમારા પાકના ફોટા લો - તમને વધુ સારી કિંમત મળશે",
    tipUpdatePrices: "સલાહ: નિયમિતપણે કિંમતો અપડેટ કરતા રહો",
    tipGoodCustomerService: "યાદ રાખો: ગ્રાહકો સાથે સારા સંબંધો રાખો",
    quantity: "માત્રા",
    price: "કિંમત",
    quality: "ગુણવત્તા",
    location: "સ્થાન",
    added: "ઉમેર્યું",
    edit: "સંપાદન કરો",
    buyer: "ખરીદાર",
    crop: "પાક",
    amount: "રકમ",
    date: "તારીખ",
    phone: "ફોન",
    call: "કૉલ કરો",
    available: "ઉપલબ્ધ",
    sold: "વેચાયું",
    confirmed: "પુષ્ટિ થઈ",
    pending: "બાકી",
    delivered: "પહોંચાડ્યું",
    back: "પાછળ",
    profile: "પ્રોફાઇલ",
    distributorDashboard: "વિતરક ડેશબોર્ડ",
    manageDistributionNetwork: "તમારા વિતરણ નેટવર્ક અને લોજિસ્ટિક્સનું વ્યવસ્થાપન કરો",
    totalInventory: "કુલ ઇન્વેન્ટરી",
    revenue: "રાજસ્વ",
    addInventory: "ઇન્વેન્ટરી ઉમેરો",
    scheduleDelivery: "ડિલિવરી શેડ્યૂલ કરો",
    inventory: "ઇન્વેન્ટરી",
    logistics: "લોજિસ્ટિક્સ",
    recentActivity: "તાજેતરની પ્રવૃત્તિ",
    inventoryStatusUpdated: "ઇન્વેન્ટરી સ્થિતિ અપડેટ થઈ",
    deliveryCompleted: "ડિલિવરી પૂર્ણ થઈ",
    distributionTips: "વિતરણ ટિપ્સ",
    tipKeepTrackOfInventory: "ટિપ: સ્ટોકઆઉટ ટાળવા માટે ઇન્વેન્ટરી સ્તરો પર નજર રાખો",
    adviceOptimizeRoutes: "સલાહ: ખર્ચ ઘટાડવા માટે ડિલિવરી માર્ગોને ઑપ્ટિમાઇઝ કરો",
    rememberGoodSupplierRelations: "યાદ રાખો: સપ્લાયરો સાથે સારા સંબંધો રાખો",
    product: "ઉત્પાદન",
    supplier: "સપ્લાયર",
    inStock: "સ્ટોકમાં",
    outOfStock: "સ્ટોક ખતમ",
    inTransit: "પરિવહનમાં",
    track: "ટ્રેક કરો",
    deliverySchedule: "ડિલિવરી શેડ્યૂલ",
    delivery: "ડિલિવરી",
    vehicleStatus: "વાહન સ્થિતિ",
    truckA: "ટ્રક એ",
    truckB: "ટ્રક બી",
    vanC: "વેન સી",
    maintenance: "રખરખાવ",
    retailerDashboard: "રિટેલર ડેશબોર્ડ",
    manageRetailOperations: "તમારા રિટેલ ઓપરેશન્સ અને ગ્રાહક સંબંધોનું વ્યવસ્થાપન કરો",
    totalProducts: "કુલ ઉત્પાદનો",
    customerRating: "ગ્રાહક રેટિંગ",
    sales: "વેચાણ",
    addProduct: "ઉત્પાદન ઉમેરો",
    manageStore: "સ્ટોર મેનેજ કરો",
    customerSupport: "ગ્રાહક સહાયતા",
    myProducts: "મારા ઉત્પાદનો",
    customers: "ગ્રાહકો",
    productStatusUpdated: "ઉત્પાદન સ્થિતિ અપડેટ થઈ",
    customerReviewReceived: "ગ્રાહક સમીક્ષા મળી",
    retailTips: "રિટેલ ટિપ્સ",
    tipKeepProductsFresh: "ટિપ: ગ્રાહકોને આકર્ષિત કરવા માટે ઉત્પાદનોને તાજા અને સારી રીતે પ્રદર્શિત રાખો",
    adviceMaintainSupplierRelations: "સલાહ: વધુ સારી કિંમતો માટે સપ્લાયરો સાથે સારા સંબંધો રાખો",
    rememberCustomerService: "યાદ રાખો: નિષ્ઠા બનાવવા માટે ગ્રાહક સેવા મહત્વપૂર્ણ છે",
    category: "શ્રેણી",
    customer: "ગ્રાહક",
    contactCustomer: "સંપર્ક કરો",
    topCustomers: "ટોચના ગ્રાહકો",
    ordersThisMonth: "આ મહિનામાં ઓર્ડર",
    vip: "વીઆઈપી",
    regular: "નિયમિત",
    new: "નવું",
    customerFeedback: "ગ્રાહક પ્રતિભાવ",
    excellentQuality: "ઉત્તમ ગુણવત્તાના ઉત્પાદનો!",
    goodService: "સારી સેવા, ઝડપી ડિલિવરી",
    processing: "પ્રક્રિયા કરી રહ્યું છે",
    shipped: "મોકલ્યું",
    inStock: "સ્ટોકમાં",
    inTransit: "પરિવહનમાં",
    scheduled: "શેડ્યૂલ કર્યું"
  },
  // Additional Indian languages with key translations
  kn: {
    heroSubtitle: "ಕೃಷಿಯ ಭವಿಷ್ಯಕ್ಕೆ ಸ್ವಾಗತ",
    heroTitle: "ಮಾರಾಟಗಾರರ ಸ್ಥಳ",
    whyChoose: "ಫಾರ್ಮ್ ಪೋರ್ಟಲ್ ಏಕೆ ಆರಿಸಬೇಕು?",
    whyChooseDesc: "ನಮ್ಮ ಪ್ಲಾಟ್ಫಾರ್ಮ್ ವಿಶೇಷವಾಗಿ ರೈತರಿಗಾಗಿ ವಿನ್ಯಾಸಗೊಳಿಸಲಾಗಿದೆ, ಇದು ಆಧುನಿಕ ಕೃಷಿಯಲ್ಲಿ ಯಶಸ್ವಿಯಾಗಲು ನಿಮಗೆ ಅಗತ್ಯವಾದ ಎಲ್ಲಾ ಸಾಧನಗಳನ್ನು ಒದಗಿಸುತ್ತದೆ.",
    dashboard: "ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    welcome: "ಸ್ವಾಗತ",
    logout: "ಲಾಗ್‌ಔಟ್",
    login: "ಲಾಗ್‌ಇನ್ / ಸೈನ್ ಅಪ್",
    farmerDashboard: "ರೈತ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    distributorDashboard: "ವಿತರಕ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    retailerDashboard: "ಚಿಲ್ಲರೆ ವ್ಯಾಪಾರಿ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    totalCrops: "ಒಟ್ಟು ಬೆಳೆಗಳು",
    activeOrders: "ಸಕ್ರಿಯ ಆದೇಶಗಳು",
    rating: "ರೇಟಿಂಗ್",
    earnings: "ಬಳಕೆ",
    myCrops: "ನನ್ನ ಬೆಳೆಗಳು",
    orders: "ಆದೇಶಗಳು",
    recentActivity: "ಇತ್ತೀಚಿನ ಚಟುವಟಿಕೆ",
    quantity: "ಪ್ರಮಾಣ",
    price: "ಬೆಲೆ",
    quality: "ಗುಣಮಟ್ಟ",
    location: "ಸ್ಥಳ",
    edit: "ಸಂಪಾದಿಸಿ",
    buyer: "ಖರೀದಿದಾರ",
    crop: "ಬೆಳೆ",
    amount: "ಮೊತ್ತ",
    date: "ದಿನಾಂಕ",
    phone: "ಫೋನ್",
    call: "ಕರೆ ಮಾಡಿ",
    available: "ಲಭ್ಯ",
    sold: "ಮಾರಾಟವಾಗಿದೆ",
    confirmed: "ದೃಢೀಕರಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ",
    delivered: "ವಿತರಿಸಲಾಗಿದೆ",
    back: "ಹಿಂದಕ್ಕೆ",
    profile: "ಪ್ರೊಫೈಲ್"
  },
  ml: {
    heroSubtitle: "കാർഷിക ഭാവിയിലേക്ക് സ്വാഗതം",
    heroTitle: "വിൽപ്പനക്കാരുടെ സ്ഥലം",
    whyChoose: "ഫാം പോർട്ടൽ എന്തുകൊണ്ട് തിരഞ്ഞെടുക്കണം?",
    whyChooseDesc: "ഞങ്ങളുടെ പ്ലാറ്റ്ഫോം പ്രത്യേകിച്ച് കർഷകരെ ലക്ഷ്യമിട്ടാണ് രൂപകൽപ്പന ചെയ്തിരിക്കുന്നത്, ഇത് ആധുനിക കാർഷികത്തിൽ വിജയിക്കാൻ നിങ്ങൾക്ക് ആവശ്യമായ എല്ലാ ഉപകരണങ്ങളും നൽകുന്നു.",
    dashboard: "ഡാഷ്‌ബോർഡ്",
    welcome: "സ്വാഗതം",
    logout: "ലോഗ്‌ഔട്ട്",
    login: "ലോഗിൻ / സൈൻ അപ്പ്",
    farmerDashboard: "കർഷക ഡാഷ്‌ബോർഡ്",
    distributorDashboard: "വിതരണ ഡാഷ്‌ബോർഡ്",
    retailerDashboard: "റീടെയിൽ ഡാഷ്‌ബോർഡ്",
    totalCrops: "മൊത്തം വിളകൾ",
    activeOrders: "സജീവ ഓർഡറുകൾ",
    rating: "റേറ്റിംഗ്",
    earnings: "വരുമാനം",
    myCrops: "എന്റെ വിളകൾ",
    orders: "ഓർഡറുകൾ",
    recentActivity: "സമീപകാല പ്രവർത്തനം",
    quantity: "അളവ്",
    price: "വില",
    quality: "ഗുണനിലവാരം",
    location: "സ്ഥലം",
    edit: "തിരുത്തുക",
    buyer: "വാങ്ങുന്നയാൾ",
    crop: "വിള",
    amount: "തുക",
    date: "തീയതി",
    phone: "ഫോൺ",
    call: "കോൾ ചെയ്യുക",
    available: "ലഭ്യമാണ്",
    sold: "വിറ്റു",
    confirmed: "സ്ഥിരീകരിച്ചു",
    pending: "താമസിക്കുന്നു",
    delivered: "ഡെലിവർ ചെയ്തു",
    back: "പിന്നിലേക്ക്",
    profile: "പ്രൊഫൈൽ"
  },
  pa: {
    heroSubtitle: "ਖੇਤੀਬਾੜੀ ਦੇ ਭਵਿੱਖ ਵਿੱਚ ਸਵਾਗਤ",
    heroTitle: "ਵਿਕਰੇਤਾ ਦੀ ਜਗ੍ਹਾ",
    whyChoose: "ਫਾਰਮ ਪੋਰਟਲ ਕਿਉਂ ਚੁਣਨਾ?",
    whyChooseDesc: "ਸਾਡਾ ਪਲੇਟਫਾਰਮ ਖਾਸ ਤੌਰ 'ਤੇ ਕਿਸਾਨਾਂ ਲਈ ਡਿਜ਼ਾਈਨ ਕੀਤਾ ਗਿਆ ਹੈ, ਜੋ ਤੁਹਾਨੂੰ ਆਧੁਨਿਕ ਖੇਤੀਬਾੜੀ ਵਿੱਚ ਸਫਲ ਹੋਣ ਲਈ ਲੋੜੀਂਦੇ ਸਾਰੇ ਸਾਧਨ ਪ੍ਰਦਾਨ ਕਰਦਾ ਹੈ।",
    dashboard: "ਡੈਸ਼ਬੋਰਡ",
    welcome: "ਸਵਾਗਤ",
    logout: "ਲੌਗ ਆਉਟ",
    login: "ਲੌਗ ਇਨ / ਸਾਈਨ ਅਪ",
    farmerDashboard: "ਕਿਸਾਨ ਡੈਸ਼ਬੋਰਡ",
    distributorDashboard: "ਵਿਤਰਕ ਡੈਸ਼ਬੋਰਡ",
    retailerDashboard: "ਰਿਟੇਲਰ ਡੈਸ਼ਬੋਰਡ",
    totalCrops: "ਕੁੱਲ ਫਸਲਾਂ",
    activeOrders: "ਸਰਗਰਮ ਆਰਡਰ",
    rating: "ਰੇਟਿੰਗ",
    earnings: "ਕਮਾਈ",
    myCrops: "ਮੇਰੀਆਂ ਫਸਲਾਂ",
    orders: "ਆਰਡਰ",
    recentActivity: "ਹਾਲੀਆ ਗਤੀਵਿਧੀ",
    quantity: "ਮਾਤਰਾ",
    price: "ਕੀਮਤ",
    quality: "ਗੁਣਵੱਤਾ",
    location: "ਟਿਕਾਣਾ",
    edit: "ਸੰਪਾਦਨ",
    buyer: "ਖਰੀਦਦਾਰ",
    crop: "ਫਸਲ",
    amount: "ਰਕਮ",
    date: "ਤਾਰੀਖ",
    phone: "ਫੋਨ",
    call: "ਕਾਲ ਕਰੋ",
    available: "ਉਪਲਬਧ",
    sold: "ਵਿਕਿਆ",
    confirmed: "ਪੁਸ਼ਟੀ",
    pending: "ਲੰਬਿਤ",
    delivered: "ਡਿਲੀਵਰ",
    back: "ਵਾਪਸ",
    profile: "ਪ੍ਰੋਫਾਈਲ"
  },
  or: {
    heroSubtitle: "କୃଷିର ଭବିଷ୍ୟତରେ ସ୍ୱାଗତ",
    heroTitle: "ବିକ୍ରେତାର ସ୍ଥାନ",
    whyChoose: "ଫାର୍ମ ପୋର୍ଟାଲ୍ କାହିଁକି ବାଛିବେ?",
    whyChooseDesc: "ଆମର ପ୍ଲାଟଫର୍ମ ବିଶେଷ ଭାବରେ କୃଷକମାନଙ୍କ ପାଇଁ ଡିଜାଇନ୍ କରାଯାଇଛି, ଯାହା ଆଧୁନିକ କୃଷିରେ ସଫଳ ହେବା ପାଇଁ ଆବଶ୍ୟକ ସମସ୍ତ ସାଧନ ପ୍ରଦାନ କରେ।",
    dashboard: "ଡ୍ୟାସବୋର୍ଡ",
    welcome: "ସ୍ୱାଗତ",
    logout: "ଲଗ୍ ଆଉଟ୍",
    login: "ଲଗ୍ ଇନ୍ / ସାଇନ୍ ଅପ୍",
    farmerDashboard: "କୃଷକ ଡ୍ୟାସବୋର୍ଡ",
    distributorDashboard: "ବିତରକ ଡ୍ୟାସବୋର୍ଡ",
    retailerDashboard: "ଚିଲ୍ଲରା ବିକ୍ରେତା ଡ୍ୟାସବୋର୍ଡ",
    totalCrops: "ମୋଟ ଫସଲ",
    activeOrders: "ସକ୍ରିୟ ଅର୍ଡର",
    rating: "ରେଟିଂ",
    earnings: "ଆୟ",
    myCrops: "ମୋର ଫସଲ",
    orders: "ଅର୍ଡର",
    recentActivity: "ସମ୍ପ୍ରତି କାର୍ଯ୍ୟକଳାପ",
    quantity: "ପରିମାଣ",
    price: "ମୂଲ୍ୟ",
    quality: "ଗୁଣବତ୍ତା",
    location: "ଅବସ୍ଥାନ",
    edit: "ସମ୍ପାଦନ",
    buyer: "କ୍ରେତା",
    crop: "ଫସଲ",
    amount: "ପରିମାଣ",
    date: "ତାରିଖ",
    phone: "ଫୋନ୍",
    call: "କଲ୍ କରନ୍ତୁ",
    available: "ଉପଲବ୍ଧ",
    sold: "ବିକ୍ରି",
    confirmed: "ନିଶ୍ଚିତ",
    pending: "ବିଚାରାଧୀନ",
    delivered: "ପ୍ରଦାନ",
    back: "ପଛକୁ",
    profile: "ପ୍ରୋଫାଇଲ୍"
  },
  as: {
    heroSubtitle: "কৃষিৰ ভৱিষ্যতলৈ স্বাগতম",
    heroTitle: "বিক্ৰেতাৰ স্থান",
    whyChoose: "ফাৰ্ম পৰ্টেল কিয় বাছিব?",
    whyChooseDesc: "আমাৰ প্লেটফৰ্ম বিশেষকৈ খেতিয়কসকলৰ বাবে ডিজাইন কৰা হৈছে, যিয়ে আধুনিক কৃষিত সফল হ'বলৈ আপোনাক প্ৰয়োজনীয় সকলো সা-সঁজুলি প্ৰদান কৰে।",
    dashboard: "ড্যাশবৰ্ড",
    welcome: "স্বাগতম",
    logout: "লগ আউট",
    login: "লগ ইন / ছাইন আপ",
    farmerDashboard: "খেতিয়ক ড্যাশবৰ্ড",
    distributorDashboard: "বিতৰক ড্যাশবৰ্ড",
    retailerDashboard: "খুচুৰা বিক্ৰেতা ড্যাশবৰ্ড",
    totalCrops: "মুঠ শস্য",
    activeOrders: "সক্ৰিয় অৰ্ডাৰ",
    rating: "ৰেটিং",
    earnings: "উপাৰ্জন",
    myCrops: "মোৰ শস্য",
    orders: "অৰ্ডাৰ",
    recentActivity: "সাম্প্ৰতিক কাৰ্যকলাপ",
    quantity: "পৰিমাণ",
    price: "দাম",
    quality: "গুণাগুণ",
    location: "স্থান",
    edit: "সম্পাদনা",
    buyer: "ক্ৰেতা",
    crop: "শস্য",
    amount: "পৰিমাণ",
    date: "তাৰিখ",
    phone: "ফোন",
    call: "কল কৰক",
    available: "উপলব্ধ",
    sold: "বিক্ৰী",
    confirmed: "নিশ্চিত",
    pending: "বিচাৰাধীন",
    delivered: "বিতৰণ",
    back: "পিছলৈ",
    profile: "প্ৰফাইল"
  },
  ne: {
    heroSubtitle: "कृषिको भविष्यमा स्वागत छ",
    heroTitle: "बिक्रेताको स्थान",
    whyChoose: "फार्म पोर्टल किन छान्ने?",
    whyChooseDesc: "हाम्रो प्लेटफर्म विशेष गरी किसानहरूका लागि डिजाइन गरिएको छ, जसले आधुनिक कृषिमा सफल हुन आवश्यक सबै साधनहरू प्रदान गर्छ।",
    dashboard: "ड्यासबोर्ड",
    welcome: "स्वागत",
    logout: "लग आउट",
    login: "लग इन / साइन अप",
    farmerDashboard: "किसान ड्यासबोर्ड",
    distributorDashboard: "वितरक ड्यासबोर्ड",
    retailerDashboard: "खुद्रा विक्रेता ड्यासबोर्ड",
    totalCrops: "कुल बाली",
    activeOrders: "सक्रिय आदेश",
    rating: "रेटिंग",
    earnings: "कमाई",
    myCrops: "मेरा बाली",
    orders: "आदेश",
    recentActivity: "हालैको गतिविधि",
    quantity: "मात्रा",
    price: "मूल्य",
    quality: "गुणस्तर",
    location: "स्थान",
    edit: "सम्पादन",
    buyer: "क्रेता",
    crop: "बाली",
    amount: "रकम",
    date: "मिति",
    phone: "फोन",
    call: "कल गर्नुहोस्",
    available: "उपलब्ध",
    sold: "बिक्री",
    confirmed: "पुष्टि",
    pending: "बाँकी",
    delivered: "वितरण",
    back: "पछाडि",
    profile: "प्रोफाइल"
  },
  ur: {
    heroSubtitle: "کاشتکاری کے مستقبل میں خوش آمدید",
    heroTitle: "فروخت کنندہ کی جگہ",
    whyChoose: "فارم پورٹل کیوں منتخب کریں؟",
    whyChooseDesc: "ہمارا پلیٹ فارم خاص طور پر کسانوں کے لیے ڈیزائن کیا گیا ہے، جو آپ کو جدید کاشتکاری میں کامیاب ہونے کے لیے ضروری تمام آلات فراہم کرتا ہے۔",
    dashboard: "ڈیش بورڈ",
    welcome: "خوش آمدید",
    logout: "لاگ آؤٹ",
    login: "لاگ ان / سائن اپ",
    farmerDashboard: "کسان ڈیش بورڈ",
    distributorDashboard: "ڈسٹری بیوٹر ڈیش بورڈ",
    retailerDashboard: "ریٹیلر ڈیش بورڈ",
    totalCrops: "کل فصلیں",
    activeOrders: "فعال آرڈرز",
    rating: "ریٹنگ",
    earnings: "آمدنی",
    myCrops: "میری فصلیں",
    orders: "آرڈرز",
    recentActivity: "حالیہ سرگرمی",
    quantity: "مقدار",
    price: "قیمت",
    quality: "معیار",
    location: "مقام",
    edit: "ترمیم",
    buyer: "خریدار",
    crop: "فصل",
    amount: "رقم",
    date: "تاریخ",
    phone: "فون",
    call: "کال کریں",
    available: "دستیاب",
    sold: "فروخت",
    confirmed: "تصدیق شدہ",
    pending: "زیر التواء",
    delivered: "ڈیلیور",
    back: "واپس",
    profile: "پروفائل"
  },
  si: {
    heroSubtitle: "කෘෂිකර්මයේ අනාගතයට සාදරයෙන් පිළිගනිමු",
    heroTitle: "විකුණුම්කරුවන්ගේ ස්ථානය",
    whyChoose: "ෆාම් පෝටල් ඇයි තෝරන්නේ?",
    whyChooseDesc: "අපගේ වේදිකාව විශේෂයෙන් ගොවීන් සඳහා නිර්මාණය කර ඇත, එය නවීන කෘෂිකර්මයේ සාර්ථක වීමට ඔබට අවශ්‍ය සියලුම මෙවලම් සපයයි.",
    dashboard: "ඩෑෂ්බෝඩ්",
    welcome: "සාදරයෙන් පිළිගනිමු",
    logout: "ලොග් අවුට්",
    login: "ලොග් ඉන් / සයින් අප්",
    farmerDashboard: "ගොවි ඩෑෂ්බෝඩ්",
    distributorDashboard: "බෙදාහරින්නා ඩෑෂ්බෝඩ්",
    retailerDashboard: "සිල්ලර විකුණුම්කරු ඩෑෂ්බෝඩ්",
    totalCrops: "මුළු බෝග",
    activeOrders: "ක්‍රියාකාරී ඇණවුම්",
    rating: "ශ්‍රේණිගත කිරීම",
    earnings: "ඉපැයීම්",
    myCrops: "මගේ බෝග",
    orders: "ඇණවුම්",
    recentActivity: "මෑත කාලීන ක්‍රියාකාරකම්",
    quantity: "ප්‍රමාණය",
    price: "මිල",
    quality: "ගුණත්වය",
    location: "ස්ථානය",
    edit: "සංස්කරණය",
    buyer: "ගැනුම්කරු",
    crop: "බෝග",
    amount: "ප්‍රමාණය",
    date: "දිනය",
    phone: "දුරකථනය",
    call: "ඇමතුම",
    available: "ලබා ගත හැකි",
    sold: "විකුණු",
    confirmed: "තහවුරු",
    pending: "පොරොත්තුවේ",
    delivered: "භාර දුන්",
    back: "ආපසු",
    profile: "පැතිකඩ"
  }
};

export const LanguageProvider = ({ children }) => {
  const [currentLanguage, setCurrentLanguage] = useState('en');
  const [isLoading, setIsLoading] = useState(true);

  // Load saved language preference
  useEffect(() => {
    const savedLanguage = localStorage.getItem('herbiproof_language');
    if (savedLanguage && translations[savedLanguage]) {
      setCurrentLanguage(savedLanguage);
    }
    setIsLoading(false);
  }, []);

  // Save language preference
  const changeLanguage = (languageCode) => {
    if (translations[languageCode]) {
      setCurrentLanguage(languageCode);
      localStorage.setItem('herbiproof_language', languageCode);
    }
  };

  // Get translation for current language
  const t = (key) => {
    return translations[currentLanguage]?.[key] || translations['en'][key] || key;
  };

  // Get available languages
  const availableLanguages = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
    { code: 'bn', name: 'বাংলা', flag: '🇧🇩' },
    { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
    { code: 'ta', name: 'தமிழ்', flag: '🇮🇳' },
    { code: 'mr', name: 'मराठी', flag: '🇮🇳' },
    { code: 'gu', name: 'ગુજરાતી', flag: '🇮🇳' },
    { code: 'kn', name: 'ಕನ್ನಡ', flag: '🇮🇳' },
    { code: 'ml', name: 'മലയാളം', flag: '🇮🇳' },
    { code: 'pa', name: 'ਪੰਜਾਬੀ', flag: '🇮🇳' },
    { code: 'or', name: 'ଓଡ଼ିଆ', flag: '🇮🇳' },
    { code: 'as', name: 'অসমীয়া', flag: '🇮🇳' },
    { code: 'ne', name: 'नेपाली', flag: '🇳🇵' },
    { code: 'ur', name: 'اردو', flag: '🇵🇰' },
    { code: 'si', name: 'සිංහල', flag: '🇱🇰' }
  ];

  const value = {
    currentLanguage,
    changeLanguage,
    t,
    availableLanguages,
    isLoading
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};
